language: cpp

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python3
    - python3-pip

install:
# Install Conan.
- sudo pip3 install conan
# Automatic detection of your arch, compiler, etc.
- conan user
# Install cpp-coveralls.
- sudo pip3 install cpp-coveralls

script:
# Build hello-world library.
- cd helloworld
- mkdir build && cd build
- conan export .. ugnelis/stable
- conan install .. -s build_type=Debug -o coverage=True --build missing
- conan build -sf .. ..
# Go back to project root.
- cd ../../
# Build app binary.
- cd app
- mkdir build && cd build
- conan export .. ugnelis/stable
- conan install .. -s build_type=Debug --build missing
- conan build -sf .. ..

after_success:
- cd ../helloworld/build
- coveralls --root ../../ --build-root . -e bin/ -e lib/ -e package -e tests/ -E .*googletest.* -E .*CMakeFiles.* -i CMakeFiles/hello-world.dir/src > coveralls.log
