language: cpp

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python3

install:
# Install pip
- curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
- sudo python3.4 get-pip.py
# Install Conan.
- sudo pip install conan
# Automatic detection of your arch, compiler, etc.
- conan user
# Install cpp-coveralls.
- sudo pip install cpp-coveralls

script:
# Build hello-world library.
- cd helloworld
- mkdir build && cd build
- conan export .. ugnelis/stable
- conan install .. -s build_type=Debug -o coverage=True --build missing
- conan build -sf .. ..
# Go back to project root.
- cd ../../
# Build app binary.
- cd app
- mkdir build && cd build
- conan export .. ugnelis/stable
- conan install .. -s build_type=Debug --build missing
- conan build -sf .. ..

after_success:
- cd ../../
- coveralls -E .*CMakeFiles.* -e helloworld/test/ > coveralls.log
